name: Build PS2 ELF
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ps2dev/ps2dev:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: tokyo_xmb_elf
          path: tokyo_xmb.elf
